apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-dns
  namespace: monitoring
data:
  resolv.conf: |
    nameserver 10.43.0.151   # CoreDNS ClusterIP
    search svc.cluster.local
    options ndots:5
